export const EVENTOS = {
    // Eventos relacionados a guild
    INTERNO: {
        READY: "READY",
        RESUMED: "RESUMED"
    },
    INTERACOES: {
        INTERACTION_CREATE: "INTERACTION_CREATE"
    },
    GUILDS: {
        GUILD_CREATE: "GUILD_CREATE",
        GUILD_UPDATE: "GUILD_UPDATE",
        GUILD_DELETE: "GUILD_DELETE",
        GUILD_ROLE_CREATE: "GUILD_ROLE_CREATE",
        GUILD_ROLE_UPDATE: "GUILD_ROLE_UPDATE",
        GUILD_ROLE_DELETE: "GUILD_ROLE_DELETE",
        CHANNEL_CREATE: "CHANNEL_CREATE",
        CHANNEL_UPDATE: "CHANNEL_UPDATE",
        CHANNEL_DELETE: "CHANNEL_DELETE",
        CHANNEL_PINS_UPDATE: "CHANNEL_PINS_UPDATE",
        THREAD_CREATE: "THREAD_CREATE",
        THREAD_UPDATE: "THREAD_UPDATE",
        THREAD_DELETE: "THREAD_DELETE",
        THREAD_LIST_SYNC: "THREAD_LIST_SYNC",
        THREAD_MEMBER_UPDATE: "THREAD_MEMBER_UPDATE",
        THREAD_MEMBERS_UPDATE: "THREAD_MEMBERS_UPDATE",
        STAGE_INSTANCE_CREATE: "STAGE_INSTANCE_CREATE",
        STAGE_INSTANCE_UPDATE: "STAGE_INSTANCE_UPDATE",
        STAGE_INSTANCE_DELETE: "STAGE_INSTANCE_DELETE"
    },
    // Eventos relacionados a membros
    GUILD_MEMBERS: {
        GUILD_MEMBER_ADD: "GUILD_MEMBER_ADD",
        GUILD_MEMBER_UPDATE: "GUILD_MEMBER_UPDATE",
        GUILD_MEMBER_REMOVE: "GUILD_MEMBER_REMOVE",
        THREAD_MEMBERS_UPDATE: "THREAD_MEMBERS_UPDATE",
    },
    // Eventos relacionados a banimentos
    GUILD_BANS: {
        GUILD_BAN_ADD: "GUILD_BAN_ADD",
        GUILD_BAN_REMOVE: "GUILD_BAN_REMOVE"
    },
    // Eventos relacionados a integrações
    GUILD_INTEGRATIONS: {
        GUILD_INTEGRATIONS_UPDATE: "GUILD_INTEGRATIONS_UPDATE",
        INTEGRATION_CREATE: "INTEGRATION_CREATE",
        INTEGRATION_UPDATE: "INTEGRATION_UPDATE",
        INTEGRATION_DELETE: "INTEGRATION_DELETE",
    },
    // Eventos relacionados a webooks
    GUILD_WEBHOOKS: {
        WEBHOOKS_UPDATE: "WEBHOOKS_UPDATE"
    },
    // Eventos relacionados a convites
    GUILD_INVITES: {
        INVITE_CREATE: "INVITE_CREATE",
        INVITE_DELETE: "INVITE_DELETE"
    },
    // Evento relacionados a atualização de status de canal de voz
    GUILD_VOICE_STATES: {
        VOICE_STATE_UPDATE: "VOICE_STATE_UPDATE",
        VOICE_SERVER_UPDATE: "VOICE_SERVER_UPDATE"
    },
    // Evento relacionados a presença
    GUILD_PRESENCES: {
        PRESENCE_UPDATE: "PRESENCE_UPDATE"
    },
    // Evento relacionado a mensagens 
    GUILD_MESSAGES: {
        MESSAGE_CREATE: "MESSAGE_CREATE",
        MESSAGE_UPDATE: "MESSAGE_UPDATE",
        MESSAGE_DELETE: "MESSAGE_DELETE",
        MESSAGE_DELETE_BULK: "MESSAGE_DELETE_BULK"
    },
    // Evento relacionado a reações de mensagens
    GUILD_MESSAGE_REACTIONS: {
        MESSAGE_REACTION_ADD: "MESSAGE_REACTION_ADD",
        MESSAGE_REACTION_REMOVE: "MESSAGE_REACTION_REMOVE",
        MESSAGE_REACTION_REMOVE_ALL: "MESSAGE_REACTION_REMOVE_ALL",
        MESSAGE_REACTION_REMOVE_EMOJI: "MESSAGE_REACTION_REMOVE_EMOJI"
    },
    // Evento relacionado ao digitar
    GUILD_MESSAGE_TYPING: {
        TYPING_START: "TYPING_START"
    },
    // Evento relacionado aos eventos
    GUILD_SCHEDULED_EVENTS: {
        GUILD_SCHEDULED_EVENT_CREATE: "GUILD_SCHEDULED_EVENT_CREATE",
        GUILD_SCHEDULED_EVENT_UPDATE: "GUILD_SCHEDULED_EVENT_UPDATE",
        GUILD_SCHEDULED_EVENT_DELETE: "GUILD_SCHEDULED_EVENT_DELETE",
        GUILD_SCHEDULED_EVENT_USER_ADD: "GUILD_SCHEDULED_EVENT_USER_ADD",
        GUILD_SCHEDULED_EVENT_USER_REMOVE: "GUILD_SCHEDULED_EVENT_USER_REMOVE"
    }
}