/**
 * Estrutura de Grupo que é recebido pelo Discord
 */
export const Grupo_Estrutura = {
    name: '',
    large: false,
    system_channel_id: '',
    owner_id: '',
    premium_subscription_count: 0,
    afk_timeout: 0,
    max_video_channel_users: 0,
    preferred_locale: '',
    emojis: [],
    vanity_url_code: null,
    member_count: 0,
    roles: [],
    afk_channel_id: null,
    guild_hashes: {},
    system_channel_flags: 0,
    verification_level: 0,
    stage_instances: [],
    premium_progress_bar_enabled: false,
    unavailable: false,
    nsfw: false,
    discovery_splash: null,
    channels: [],
    mfa_level: 0,
    members: [],
    premium_tier: 0,
    public_updates_channel_id: null,
    explicit_content_filter: 0,
    rules_channel_id: null,
    application_command_counts: {},
    threads: [],
    joined_at: '',
    presences: [],
    hub_type: null,
    banner: null,
    id: '',
    description: null,
    guild_scheduled_events: [],
    icon: null,
    splash: null,
    features: [],
    application_id: null,
    max_members: 0,
    lazy: true,
    default_message_notifications: 0,
    embedded_activities: [],
    nsfw_level: 0,
    stickers: []
}